### ISSUE TITLE
Some issue with turtlebot battery

### ISSUE THREAD

**Issue by MathisGodard** [turtlebot/turtlebot4#139]
Hello.

I'm working at Génération Robots, and a customer has a problem with his robot : 

TurtleBot4 mobile robot (Standard version) -

"Dear sir, I hope this letter finds you well. I am writing to bring to your attention some concerns I have regarding the Turtlebot 4 that I recently received. Firstly, I noticed that the battery life of the robot seems to be shorter than what was stated in the specifications. According to the specs, the battery should last approximately 2.5 to 4 hours, depending on usage. However, when I turned on the robot after it was fully charged, it only lasted for two hours without any movement before shutting down. I was expecting it to last closer to 4 hours even without moving the robot. Is this behavior normal? Secondly, I have not yet had the opportunity to configure the robot, but the screen is showing a 0% battery level and the behaviors such as going home to the dock station are not functioning. I am unsure if this is expected behavior. Thank you for your attention to this matter. Sincerely, Pablo"

Can you help me ? 

Best regards, Mathis.

**Comment by roni-kreinin** [comment]
A significant portion of the battery drain comes from the lidar and camera. Even if the robot is not moving, the sensors are still on and drawing power. I would recommend that they update their robot to Humble to get the latest features. This includes the "Auto standby" mode for the rplidar, which makes it automatically stop spinning if nothing is subscribed to the `scan` topic. It also supports the new OAK-D start and stop services.

>Secondly, I have not yet had the opportunity to configure the robot, but the screen is showing a 0% battery level and the behaviors such as going home to the dock station are not functioning. I am unsure if this is expected behavior.

This is expected behaviour if the robot has not been configured. The base Create 3 needs to be connected to Wi-Fi.

**Comment by MathisGodard** [comment]
Thanks for this repply. 

I will tell you if the problem persist. 

Best regards, Mathis.
