### ISSUE TITLE
Turtlebot4 Raspberry Pi unreachable over Wi-Fi on first start

### ISSUE THREAD

**Issue by smatarCPR** [turtlebot/turtlebot4#192]
**Please provide the following information:**
 - OS: Unknown at this point will update soon
 - ROS Distro: Unknown at this point will update soon
 - Built from source or installed:
 - Package version: (if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE`, if from source, give commit hash)

 **Expected behaviour**
Raspberry Pi should be in AP mode with a Wi-Fi network named Turtlebot4 visible to host computer

 **Actual behaviour**
Raspberry Pi is unreachable, no display on the small screen, all LEDs are dark, no Turtlebot4 Wi-Fi network

**To Reproduce**
TB4 is docked, and powered on, center ring is white. USB-C cable between Create3 and Raspberry Pi is connected securely.

**Other notes**
Clip of TB4 docked: https://drive.google.com/file/d/102YbEdG1AAKVyjYKJZ4iiDcjREsruCI-/view
Is there a way to access the Raspberry Pi?

**Comment by yorambenhaim** [comment]
Hi.  I noticed that the RPI red LED was ON. But the small screen near the buttons was OFF (i.e No display).
Another question. What do I've to do with the SanDisk micro-SD attached to the package ??

**Comment by llyf-s** [comment]
the SanDisk is an adapter for your turtlebot's RPi ssd card, for you to install latest Pi image if necessary (1. Basic Setup)

**Comment by yorambenhaim** [comment]
Great. Thank You.
Do you think I should update/upgrade the PI image?  Is there any important added value or some other reason to do so ?
BTW. The micro-SD is on the far side of the PI board (on the other side of the USB connectors) and it is not accessible , unless I’ll uninstall the PI.

B.R.
Yoram Ben-Haim

**Comment by hilary-luo** [comment]
Hi Yoram, 

In the clip you showed the Turtlebot 4 is still booting up. You should wait until the white light stops spinning and you hear the "happy sound" and that will mean that the robot is booted up. 

Either way, please do update/upgrade the PI image following the instructions here: https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#install-latest-raspberry-pi-image 

In order to access the sd card from the raspberry pi you will need to remove the PCBA https://turtlebot.github.io/turtlebot4-user-manual/mechanical/turtlebot4.html#removing-the-pcba

We always suggest that you update the raspberry pi and create3 base upon receipt. This will ensure that you are starting with the correct ros distro for your use case and the latest software / firmware.

**Comment by hilary-luo** [comment]
Closed due to inactivity, the issue is assumed to be resolved. If this issue is still ongoing feel free to re-open the issue.
