### ISSUE TITLE
Missing package when trying to launch Rviz

### ISSUE THREAD

**Issue by TRVLabs-Axel** [turtlebot/turtlebot4#195]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Humble 1.2
 - Built from source or installed:
 - Package version: 

 **Expected behaviour**
I am new to ROS and Turtlebot and so I want to map the room I am in. Everything has worked so far, but I am having trouble with launching Rviz2. I want to be able to visualize the map as the [guide](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/generate_map.html) states. 

 **Actual behaviour**
I am able to run SLAM, but when I run the code:

ros2 launch turtlebot4_viz view_robot.launch.py

I get the error:

Package 'turtlebot4_viz' not found: "package 'turtlebot4_viz' not found, searching: ['/opt/ros/humble']"

As the error states, I do not have the package "turtlebot4_viz" which I understand. My problem is how do I get the package. Everything has worked so far and I can't find anyone who has had a similar problem. 

**To Reproduce**
Provide the steps to reproduce:
1. launch SLAM by: ros2 launch turtlebot4_navigation slam.launch.py
2. Open new terminal and try to launch Rviz by: ros2 launch turtlebot4_viz view_robot.launch.py
3. Error: Package 'turtlebot4_viz' not found: "package 'turtlebot4_viz' not found, searching: ['/opt/ros/humble']"

**Other notes**
When looking at other tutorials everyone seem to be able to just launch Rviz after launching SLAM. I do source my ROS2 environment so that is not the issue.

**Comment by hilary-luo** [comment]
Please ensure that you are attempting to launch rviz on a pc with `ros-galactic-turtlebot4-desktop` installed (as per the user pc setup instructions https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html).

The turtlebot4_viz package is a part of Turtlebot 4 Desktop and must be run on a pc with a display. For this reason, it is not found on the robot itself. You will also need to set up the networking in order to ensure that you will be able to see the robot information from your pc https://turtlebot.github.io/turtlebot4-user-manual/setup/networking.html.

If this addresses your concerns please close the issue, if not let me know.

**Comment by TRVLabs-Axel** [comment]
I did the setup again and running `sudo apt install ros-humble-turtlebot4-desktop` seems to have solved the issue. Thanks
