### ISSUE TITLE
Turtlebot4 with defective battery.

### ISSUE THREAD

**Issue by MathisGodard** [turtlebot/turtlebot4#199]
Hello,

One of you customer bought 4 turtlebot4 the 21/07/2022 and he has a problem with one. 

"One of the robots’ batteries is not working anymore. The robot refuses to charge above 10%. We have tried to switch the docking system and discharge the battery completely before retrying but we still have the same issue. Is there a way to get this fixed?"

How can we resolve the problem ? 

Best regards, Mathis.

**Comment by hilary-luo** [comment]
These instructions assume you have a standard turtlebot 4, the setup looks a little different if you are using a turtlebot lite. 

Please remove the battery for 15 minutes to allow the system to reset. 
1. access the bottom of the turtlebot and unscrew the 5 screws shown below
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/da4d9706-13ad-496b-b60f-23d700dd910d)
2. remove the bottom plate, depress the battery retaining tab and remove the battery
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/b678989a-7409-4c45-8e14-d21d5f2eec32)
3. after 15 minutes, reinstall the battery and screw the baseplate back on
4. Remove the cargo bay and remove the create 3 user interface board. This will mean that the raspberry pi and other peripherals will no longer turn on. 
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/82341e91-9e6a-4ce8-a103-af6972749037)
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/6380cd56-a05b-47aa-a8ba-4f42be601125)
5. Dock the robot to charge and leave it to charge to full charge. 
6. Once the robot is fully charged, shut down the robot.
7. Reinstall the user interface board (as shown above) and reinsert the cargo bay.

**Comment by MathisGodard** [comment]
Hello,

thanks for the feedback. We do not have a micro HDMI cable at hand and the booting process might very well be faulty.

Getting a new SD card would be very appreciated, this could hopefully solve all the issues we have been having.

Cordially, Mathis.

**Comment by hilary-luo** [comment]
Hi Mathis,

When you say the booting process may be faulty are you referring only to the raspberry pi? Can you confirm that the create3 is booting properly (spinning white light until it plays a "happy sound" and then the light is solid?).

Have you completely reconnected the user interface board and can see the raspberry pi board turning on? (power light near the display and on the raspberry pi board itself). 

If you can confirm all of the above, please remove the sd card and re-image it with the latest software as described here: https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#install-latest-raspberry-pi-image . Ensure that you choose the correct version to match your robot (lite vs standard). This will reset the software to the original state. 

If you have a Turtlebot4 Standard then you will need to remove the pcba in order to access the raspberry pi (https://turtlebot.github.io/turtlebot4-user-manual/mechanical/turtlebot4.html#removing-the-pcba)

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
