### ISSUE TITLE
The Create3 BT device not identified either by my Mobile phone or the Laptop.

### ISSUE THREAD

**Issue by yorambenhaim** [turtlebot/turtlebot4#208]
Host : Lenovo Intel I7 laptop/ Ubuntu 22.04 / Humble 

Robot: TurtleBot4 Create3 G4.5 FW. 

The Create3 BT device not identified either by my Mobile phone or the Laptop.
Attached picture of the BT/USB switch position.

Is it necessary if I just want to write a code to control the robot through ROS2-Humble over WIFI ?

Thanks in advance
Yoram Ben-Haim

**Comment by hilary-luo** [comment]
Hello,

You do not need to use bluetooth in order to control the robot, in fact you need to be using wifi to control the robot using ROS2. I don't see an image but please ensure that the BT/USB switch is set to the USB option. This is important for the communication between the create3 and the raspberry pi. 

In order to learn how to control the robot please start with the [Driving Tutorial](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/driving.html). This will show you how to drive the robot using the keyboard on your pc. I would then encourage you to go through the tutorials in order. Specifically, the [Turtlebot 4 Navigator Tutorials](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/turtlebot4_navigator.html) show much more sophisticated ways of controlling your turtlebot both autonomously through code and directly from your pc. Those codes are good ones to start from for creating your own custom routines.

**Comment by yorambenhaim** [comment]
> Hello,
> 
> You do not need to use bluetooth in order to control the robot, in fact you need to be using wifi to control the robot using ROS2. I don't see an image but please ensure that the BT/USB switch is set to the USB option. This is important for the communication between the create3 and the raspberry pi.
> 
> In order to learn how to control the robot please start with the [Driving Tutorial](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/driving.html). This will show you how to drive the robot using the keyboard on your pc. I would then encourage you to go through the tutorials in order. Specifically, the [Turtlebot 4 Navigator Tutorials](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/turtlebot4_navigator.html) show much more sophisticated ways of controlling your turtlebot both autonomously through code and directly from your pc. Those codes are good ones to start from for creating your own custom routines.

Thank you very much hilary-luo. 
The robot is a brand new unit and I wish to have results ASAP. But , I ran into another issue. 
(which is not necessarily related to the previous topic). The RPI small display panel (at the front) apparently not working. Furthermore, I was unable to perform a SSH to the RPI and also the Turtlebot4 wifi does not appear. However, I saw that the RPI power red-led is on. According to the Getting-start tutorial is should work at the very beginning. 
How can I fix it or handle it by my self (Im an engineer) ? Can I control the Robot through my ROS2 control routine without using the RPI ?
Appreciate your willing to help me. 
Yoram Ben-Haim

**Comment by hilary-luo** [comment]
When you say that you were unable to ssh to the RPI that you mean over wifi.
First verify that the create3 interface board is inserted all of the way and that the raspberry pi is powered on (either by the power light being on or when you connect).
Next, I would suggest reimaging the raspberry pi with the latest software. https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#recovering-the-raspberry-pi . Ensure that when you choose the raspberry pi image that you choose the turtlebot4_standard_humble option.

Following this the display should be working and you should be able to connect to the wifi through access point mode. 

You can run the Create3 independently without using any of the turtlebot functionality but you would be limited on what you can do with it. I would really suggest going through the troubleshooting to get the full system up and running.

**Comment by yorambenhaim** [comment]
Thank you 🙏
