### ISSUE TITLE
ROBOTIS OpenMANIPULATOR-X with Turtlebot4

### ISSUE THREAD

**Issue by Robo52** [turtlebot/turtlebot4#291]
Hi everyone, as the title states, I am wondering if it is possible to run a ROBOTIS OpenMANIPULATOR-X with a Turtlebot4 standard running ROS2 Humble. Thanks!

**Comment by hilary-luo** [comment]
In order to use a device with the Turtlebot4 in ROS 2 Humble, that device needs to also support ROS 2 Humble or you need to be prepared to add that functionality yourself. I do not see any indication that ROBOTIS is supporting Humble with that product so it would not work out of the box. I imagine that you could update the foxy packages to humble and get this working with some time and effort.

There are products out there that indicate that they support ROS 2 Humble such as https://www.trossenrobotics.com/pincherx-100-robot-arm.aspx, although do not consider this an endorsement as I have not used this arm before. It is an example of an arm that indicates ROS 2 Humble support.

Also be aware that if you are powering anything off of the turtlebot you need to make sure that it will work with the User Power quoted here: https://turtlebot.github.io/turtlebot4-user-manual/electrical/pcba.html#user-power
