### ISSUE TITLE
Turtelbot 4 Cannot charge without payload active.

### ISSUE THREAD

**Issue by Simba185** [turtlebot/turtlebot4#299]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS Distro: Humble
 - Built from source or installed: Installed
 

 **Expected behaviour**
Dock TB4
Press Power button
Device Turns off

 **Actual behaviour**
Dock TB4
Press Power button
Nothing happens

**To Reproduce**
Provide the steps to reproduce:
Dock TB4.

**Other notes**
According to all Clearapth manuals and Create 3 manual, there is no way to charge the TB4 without the payload active.

Considering the RPLidar uses a belt, ( just a bit better than the rubber bands used in previous models) the device will wear out due to mechanical wear prematurely as it will operate continually in charging and device operation.

Other than to unplug the lidar or the entire payload (remove card from storage bay). There really should be an option to shutdown the payload during charging. ( say set a sleep or time-out function.)

Its clear this was overlooked during the design of the Turtlebot 4.

**Comment by roni-kreinin** [comment]
The turtlebot4 node implements a power saving mode where it will turn the camera off when the robot docks, and turn it back on when it undocks. For the RPLIDAR, the driver exposes the `auto_standby` parameter [set here](https://github.com/turtlebot/turtlebot4_robot/blob/803ecd34c048f181fe758d993f7e26bd17e92e90/turtlebot4_bringup/launch/rplidar.launch.py#L34) which makes the RPLIDAR stop spinning when there are no active subscribers on the `/scan` topic.

By default these power saving options are enable on turtlebot4. The reason your lidar continues to spin is likely because you have the turtlebot4 diagnostics node enabled. This node subscribes to `/scan` to monitor the scan frequency, so the lidar continues to spin. Diagnostics can be disabled in the `turtlebot4_setup` tool. See https://github.com/turtlebot/turtlebot4/issues/286 for more details.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
