### ISSUE TITLE
Adding Ultrasound Sensors into Starndard Turtlebot4 

### ISSUE THREAD

**Issue by Itsasne88** [turtlebot/turtlebot4#308]
Hello,

I am currently integrating ultrasound sensors into the Turtlebot4 Standard robot. Having successfully connected and configured the sensors, my next step is to initiate the sensor topic upon the robot's startup. I believe the robot's services are started with the _turtlebot4_bringup_ package, particularly the _standard.launch.py_ file. However, I haven't been able to locate this package on the robot. Could you please confirm if I am on the right track? If so, could you provide information on the location of the _turtlebot4_bringup_ package and the _standard.launch.py_ file?

Additionally, I need to modify the URDF of the robot to incorporate the sensor positions. If you could guide me to the location of that file as well, I would greatly appreciate it.

Thank you in advance.

Best regards,
Itsasne

**Comment by hilary-luo** [comment]
You are indeed on the right track. To make those changes you should build the packages from source. If you did locate the files and modify them, they would be overwritten when you update the packages next. A rough outline of steps are (I have erred towards a mid level of detail not knowing your background with programming / ROS and to help others who may read this):

**Building from source**
1. Create a workspace on your robot
2. Clone the [turtlebot4](https://github.com/turtlebot/turtlebot4) and [turtlebot4_robot](https://github.com/turtlebot/turtlebot4_robot) packages into it, source ros and then build the packages
3. Once you can successfully built your packages then you can move on to modifying them

**Modifying the packages**
1. As you deduced the turtlebot4_bringup package has the [launch files](https://github.com/turtlebot/turtlebot4_robot/tree/humble/turtlebot4_bringup/launch), specifically `standard.launch.py` which is the top level launch file. 
2. The urdf files are found in the [turtlebot4 common package](https://github.com/turtlebot/turtlebot4/tree/humble/turtlebot4_description/urdf). Specifically [turtlebot4.urdf.xacro](https://github.com/turtlebot/turtlebot4/blob/humble/turtlebot4_description/urdf/standard/turtlebot4.urdf.xacro) is going to be your top level urdf.

**Setting up the robot to use the locally built packages**
1. Link to your custom workspace using the turtlebot4-setup tool:
    - run turtlebot4-setup
    - navigate to ROS Setup -> Bash Setup
    - select WORKSPACE_SETUP
    - enter the path to your local setup.bash for your workspace. This will allow the turtlebot4 setup tool to locate and source these packages. e.g. /home/administrator/ros_ws/install/setup.bash
2. Reinstall the turtlebot4 service using the turtlebot4-setup tool under Robot Upstart -> Install.
    - run turtlebot4-setup
    - navigate to ROS Setup -> Robot Upstart
    - select Install and agree as necessary
Now your robot should automatically run your local build whenever it is turned on.

During local testing you may want to be able to launch directly instead of always restarting the service to adopt new changes. You can do this, just go under the Robot Upstart section again and stopping the service. Then you can call the launch files directly as per normal without interference and see the output in your terminal.

**Comment by Itsasne88** [comment]
Hi @hilary-luo,

Thank you for your quick response. I haven't had the chance to try your solution yet, but I will let you know as soon as I can.

Thanks again,
Itsasne
