### ISSUE TITLE
turtlebot4 not showing up on Rviz and not connecting to wifi

### ISSUE THREAD

**Issue by Akalpita30** [turtlebot/turtlebot4#316]
Please provide the following information:
OS: Ubuntu version 22.04
ROS Distro: Humble
Built from source
Package version: H.2.2

Expected behaviour
Turtlebot4 shows up on rviz for creating a new map.

Actual behaviour
on running command-ros2 launch turtlebot4_viz view_robot.launch.py, ros2 launch turtlebot4_viz view_model.launch.py  : the bot doesnt show up on the window i tried running the other command too the results were same. on checking the wi-fi connection the irobot doesn't show connected. i tried to reboot the RPi and unplug it for a day, charging the robot, changing the battery but it doesn't change anything. i tried to connect to the icreate logs for ntp configs but was unable to connect to the server.
This is the screenshot of the rviz window,
![Screenshot from 2023-12-04 19-20-28](https://github.com/turtlebot/turtlebot4/assets/87574208/0fe3eca1-6a30-4e51-a656-abbd2b202511)

Turtlebot4 isn't showing up on the wi-fi clients list.
![Screenshot from 2023-12-04 19-20-54](https://github.com/turtlebot/turtlebot4/assets/87574208/c00fbfe2-f37b-4a81-878c-9d99ce892469)

Screenshot from icreate server
![Screenshot from 2023-12-04 19-21-21](https://github.com/turtlebot/turtlebot4/assets/87574208/c46244d6-d88b-43ef-886a-e7ecdf7b1e58)

After running diagnostics, it shows a lot of hazards
![Screenshot from 2023-12-04 19-55-17](https://github.com/turtlebot/turtlebot4/assets/87574208/32ef9cdb-b6ed-491d-a62c-c52fef8acb95)

screenshot from terminals
ros2 launch turtlebot4_navigation slam.launch.py
![Screenshot from 2023-12-04 19-58-39](https://github.com/turtlebot/turtlebot4/assets/87574208/da3a7871-b592-4135-ac96-de4b65cc9026)

ros2 launch turtlebot4_viz view_robot.launch.py
![Screenshot from 2023-12-04 20-01-29](https://github.com/turtlebot/turtlebot4/assets/87574208/852c2bd0-7cc6-4f22-b122-b20cf2586e30)

**Comment by hilary-luo** [comment]
@Akalpita30 when you say that the turtlebot is not showing as connected, do you mean the create3 base or the raspberry pi? In your wifi client list one does show up as 'ubuntu' which I would assume is the raspberry pi.

Can you ssh into the robot and/or are you receiving any topics? It sounds like you have networking issues that need to be resolved first before you can run any navigation / rviz windows.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.

**Comment by MikitaSaladukha** [comment]
Hello. Have the same problem. I'm trying to look on turtlebot4 model by command
![Снимок экрана от 2024-05-22 16-53-42](https://github.com/turtlebot/turtlebot4/assets/38906608/9f8da5e5-e8b9-4255-b220-6cd8d0ba8d12)


When window is opened, I see the folllowing:
![Снимок экрана от 2024-05-22 16-52-26](https://github.com/turtlebot/turtlebot4/assets/38906608/39ac4629-7f98-45e1-9635-95f30e74544e)


So main problem, I suspect is in Global Status
**Fixed Frame**
No tf data. Actual error: Frame [base_link] does not exist

Also.
When I run 
**ros2 launch turtlebot4_ignition_bringup ignition.launch.py**
turtlebot 4 model is not showing. World is showing normally. 

OS: Ubuntu version 22.04
ROS Distro: Humble
Built from deb package
Package version: H.2.2

Expected behaviour
Turtlebot4 model is showed

**Comment by MikitaSaladukha** [comment]
The above problem seems to appear after I've tried to switch to lite model of robot when starting ignition gazebo
