### ISSUE TITLE
The navigation goal and the coordinates of Turtlebot 4 confirmed through /amcl_pose upon arrival are different.

### ISSUE THREAD

**Issue by gustn6591** [turtlebot/turtlebot4#382]
### Describe the the feature you would like

When creating a package and creating a node that moves Turtlebot 4 to a single coordinate, I want to move it so that the coordinates entered are the same as the coordinates confirmed through /amcl_pose.

### Motivation and impact

Depending on the direction of movement, an error occurs between the coordinates of the goal and the destination point as much as the radius of Turtlebot 4.

**Comment by hilary-luo** [comment]
@gustn6591 Thank you for sharing your thoughts. This is not being accepted as a product enhancement because you are describing the Nav2 goal tolerance setting. This is generic Nav2 configuration that any user can do (and not Turtlebot4 functionality). Specifically, this is set for the turtlebot4 in the [nav2.yaml](https://github.com/turtlebot/turtlebot4/blob/d6881758863264ca32cf2a965c2a0ddfb2cc3094/turtlebot4_navigation/config/nav2.yaml#L95)
