### ISSUE TITLE
Nav2 not working correctly

### ISSUE THREAD

**Issue by ebear11** [turtlebot/turtlebot4#90]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 20.04) Ubuntu 20.04
 - ROS Distro: (e.g. Galactic) galactic

 When I run the Nav2 command found in the documentation ("ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=office.yaml")  I am left with a global error "no tf data found." I also notice the comm light on the turtlebot4 turns off. 
The create 3 logs say "ddsi_udp_conn_write to udp/192.168.1.126:46503 failed with retcode -3." (It repeats that with many different port numbers) I was able to save the map and actually map the environment fine but whenever I run the command found in the guide the comm light always turns off and that same error appears in the create 3 logs. I looked at issue #59 but I could not try switching the middleware as I could not find any instructions on how to configure the PC to use Fast RTPS. I am just a high school student trying to figure out the workings of how ROS2 works.

**Comment by roni-kreinin** [comment]
To us FastRTPS on your PC you just need to `export RMW_IMPLEMENTATION=rmw_fastrtps_cpp`. If you don't have fastrtps installed you can install it with `sudo apt install ros-galactic-rmw-fastrtps-cpp`.

**Comment by ebear11** [comment]
Thank you for the reply. I was able to successfully switch the middleware and I tested that it worked with manually driving it around, but I am still unable to navigate. The error that seems to be popping up in rviz is frame [map] not found. To be more specific, the terminal says,"timed out waiting for transform between base_link and odom to become available" The other part of the error mentions that the frame odom being passed to canTransform and that the target_frame does not exist. The light still turns off but with a new symptom. The main light turns solid red for a few seconds then back to normal but I can not drive the robot around after that. sometimes when it happens I can't even turn the robot off. The power button does not do anything no matter what I try to it.  I am almost starting to wonder whether or it is a hardware fault but I am going to assume it is something I am doing wrong.

**Comment by JasmineRosselliSUPSI** [comment]
I recently had a similar problem after updating the create3 (but only a few weeks leater, so it my not be the cause) to the newer version (G.3.1). I have the versions ubuntu 20.04 Focal and ROS2 Galactic installed on the Rpi of my turtlebot4.

The similarities are:
- solid red light and turtlebot4 unable to react to any stimulus
- navigation issues
- the turtlebot4 CAN be driven using `ros2 run teleop_twist_keyboard teleop_twist_keyboard`
- the turtlebot4 CAN create maps (`ros2 launch turtlebot4_navigation slam_sync.launch.py`)
- the turtlebot4 CANNOT be driven using `ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=<map_name>.yaml`

One more problem I have:
- /docking and /undocking don't work from script or through command line (action send_goals) -> BUT the robot is actually able to perform /dock and /undock using create3 physical buttons.

If run from script or terminal, it returns message:
'_Goal_rejected_' 

If turtlebot4 is not on docker station, always respond with `Goal_rejected` but sometimes perform dock anyway.

(Edited):
Here I leave the terminal response when I try to perform /dock or /undock from script:

`$ ros2 run navigation_test test_crash`
_[INFO] [1674208103.292496984] [basic_navigator]: Docking before initialising pose
[INFO] [1674208103.294937391] [basic_navigator]: Docking...
[ERROR] [1674208103.304079597] [basic_navigator]: Dock goal rejected
Traceback (most recent call last):
  File "/home/<my_raspberry_name>/turtlebot4_ws/install/navigation_test/lib/navigation_test/test_crash", line 11, in <module>
    load_entry_point('navigation-test==0.0.0', 'console_scripts', 'test_crash')()
  File "/home/<my_raspberry_name>/turtlebot4_ws/install/navigation_test/lib/python3.8/site-packages/navigation_test/test_dock_undock_crash.py", line 21, in main
    navigator.dock()
  File "/home/<my_raspberry_name>/turtlebot4_ws/install/turtlebot4_navigation/lib/python3.8/site-packages/turtlebot4_navigation/turtlebot4_navigator.py", line 214, in dock
    while not self.isDockComplete():
  File "/home/<my_raspberry_name>/turtlebot4_ws/install/turtlebot4_navigation/lib/python3.8/site-packages/turtlebot4_navigation/turtlebot4_navigator.py", line 238, in isDockComplete
    if self.dock_result_future is None or not self.dock_result_future:
AttributeError: 'TurtleBot4Navigator' object has no attribute 'dock_result_future'_

---
Here some more details
--- 

At first I did the update of create3 to solve nav2 a problem (often amcl_pose parameter wasn't publishing and the only way to fix that was to reboot the robot multiple times).
For some weeks this worked well.

BUT! 

I now face too with navigation issues, with solid red light and turtlebot4 unable to receive or send commands, even from physical buttons. To momentarily fix the issue, the only thing that worked was to take off the battery and reboot the system.

I also started to notice problems at action and service level, which seem to be cumulative. The more action and service servers are compromised, the more others follow.

From create3 log i receive both **retcode -3** and **retcode -1** errors. I already tried to install older version of create3 and back to new, but in neither case worked.

If I test turtlebot4 behavior running `ros2 run turtlebot4_tests ros_tests`,
I get stuck at tests 3 and 4.
The messages I get are basically the same (here some examples):

_- [WARN] [1674139895.970490189] [turtlebot4_ros_tests]: Ignoring unexpected goal response. There may be more than one action server for the action '/drive_distance'_ 

_- [WARN] [1674139974.115775685] [turtlebot4_ros_tests]: Ignoring unexpected result response. There may be more than one action server for the action '/dock'_ 

Test 3 actually works, beside the WARN messages, but on test 4 the turtlebot4 performs undock and then crash.

When I exit the test terminal, the following message error occurs:

_Exception ignored in: <function ActionClient.__del__ at 0xffff8a07c940>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/action/client.py", line 588, in __del__
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/action/client.py", line 581, in destroy
rclpy._rclpy_pybind11.InvalidHandle: cannot use Destroyable because destruction was requested_

Nodes and packages not related to navigation work fine.

Could this be a problem related to the create3 base or to the turtlebot4?
Has anyone been able to solve this problem?

**Comment by JasmineRosselliSUPSI** [comment]
My navigation issues may have been fixed.
The possible cause of these problems was probably a defective SD card.
See https://github.com/iRobotEducation/create3_docs/issues/316 to get full description of resolution.

**Comment by roni-kreinin** [comment]
@ebear11 Did you manage to fix the issue?

If not, try using the FastDDS discovery server as mentioned [here](https://github.com/turtlebot/turtlebot4/issues/26#issuecomment-1416310217).

**Comment by ebear11** [comment]
Not yet. I think our router might have been acting up on us after I realized I connected the pi to the 2.4 network and when connecting to the 5G network it failed to ping anything. If a router change does not work I will trying using that
